### ISSUE TITLE
submodule checkout required or Podfile missing?

### ISSUE THREAD

**Issue by demianturner** [insidegui/UXKitDemo#1]
I'd love to give this a go, some reps are missing: http://take.ms/RKzfr

**Comment by insidegui** [comment]
I removed the dependency on ReactiveCocoa, it was only used by the FlickrSearch framework because I grabbed it from another project which uses RC ><

**Comment by demianturner** [comment]
Thanks for the update.  Am updating my Xcode 8.0 to latest GM as compile still not working http://take.ms/bStNVa

**Comment by insidegui** [comment]
Yeah it will only work on the latest Xcode GM because of last-minute Swift 3 changes.

**Comment by demianturner** [comment]
Got it running, performance is amazing, thumbnail caching is quite interesting too, it's a crime that this framework is not being released to devs!

**Comment by insidegui** [comment]
Definitely, lots of iOS developers would feel more comfortable writing macOS apps if this framework was made public.
